services:
  nginx:
    build: .docker/nginx
    volumes:
      - ./api:/srv/app
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .docker/nginx/conf.d:/etc/nginx/conf.d
      - .docker/nginx/certs:/etc/nginx/certs
    depends_on: [ php ]
    hostname: jish.io
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp

  php:
    build: .docker/php
    working_dir: /srv/app
    volumes:
      - ./api:/srv/app
    depends_on: [ database ]

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  node:
    build: .docker/node
    working_dir: /project
    volumes:
      - ./app/:/project
      - .docker/nginx/certs:/certs

volumes:
  database_data:
