api_platform:
    title: Jisho.fr API
    version: 1.0.0
    formats:
        json: ['application/json']
    error_formats:
        jsonproblem: ['application/problem+json']
    docs_formats:
        json: ['application/json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    keep_legacy_inflector: false
    use_symfony_listeners: true
    resource_class_directories:
        - '%kernel.project_dir%/src/Deck/ApiResource'
        - '%kernel.project_dir%/src/Dictionary/ApiResource'
