when@dev: &dev
    # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
    zenstruck_foundry:
        make_factory:
            default_namespace: 'App\Common\Foundry\Factory'
        make_story:
            default_namespace: 'App\Common\Foundry\Story'
        persistence:
            # Flush only once per call of `PersistentObjectFactory::create()`
            flush_once: true

when@test: *dev
