<?php

declare(strict_types=1);

return [
    ['たべます', 'manger', 'verbe'],
    ['のみます', 'boire', 'verbe'],
    ['いきます', 'aller', 'verbe'],
    ['おきます', 'se lever', 'verbe'],
    ['はなします', 'parler', 'verbe'],
    ['します', 'faire', 'verbe'],
    ['ききます', 'écouter', 'verbe'],
    ['よみます', 'lire', 'verbe'],
    ['かきます', 'écrire', 'verbe'],
    ['みます', 'regarder, voir', 'verbe'],
    ['ねます', 'se coucher', 'verbe'],
    ['かえります', 'rentrer, retourner', 'verbe'],
    ['おわります', 'terminer', 'verbe'],
    ['あけます', 'ouvrir', 'verbe'],
    ['みせます', 'montrer', 'verbe'],
    ['まちます', 'attendre', 'verbe'],
    ['きれい', 'beau, propre', 'adjectif'],
    ['せまい', 'étroit', 'adjectif'],
    ['おおきい', 'grand', 'adjectif'],
    ['ちいさい', 'petit', 'adjectif'],
    ['ながい', 'long', 'adjectif'],
    ['みじかい', 'court', 'adjectif'],
    ['たかい', 'cher', 'adjectif'],
    ['やすい', 'bon marché', 'adjectif'],
    ['あつい', 'chaud', 'adjectif'],
    ['さむい', 'froid', 'adjectif'],
    ['あたらしい', 'neuf, nouveau', 'adjectif'],
    ['ふるい', 'vieux', 'adjectif'],
    ['あかるい', 'clair', 'adjectif'],
    ['くらい', 'sombre', 'adjectif'],
    ['かるい', 'léger', 'adjectif'],
    ['おもい', 'lourd', 'adjectif'],
    ['いい', 'bien, bon', 'adjectif'],
    ['わるい', 'mauvais', 'adjectif'],
    ['うるさい', 'bruyant', 'adjectif'],
    ['しずか', 'calme, tranquille', 'adjectif'],
    ['きたない', 'sale', 'adjectif'],
    ['ひろい', 'étendu, spacieux', 'adjectif'],
    ['がくせい', 'étudiant'],
    ['かいしゃいん', 'employé', 'métier'],
    ['ぎんこういん', 'employé de banque', 'métier'],
    ['いしゃ', 'docteur', 'métier'],
    ['べんごし', 'avocat', 'métier'],
    ['かいけいし', 'comptable', 'métier'],
    ['けんちくか', 'architecte', 'métier'],
    ['ぎし', 'ingénieur', 'métier'],
    ['けいかん', 'agent de police', 'métier'],
    ['かんごし', 'infirmière', 'métier'],
    ['はいしゃ', 'dentiste', 'métier'],
    ['ひしょ', 'secrétaire', 'métier'],
    ['てんいん', 'vendeur', 'métier'],
    ['ぎんこう', 'banque'],
    ['ゆうびんきょく', 'bureau de poste'],
    ['がっこう', 'école'],
    ['びょういん', 'hôpital'],
    ['きっさてん', 'café'],
    ['としょかん', 'bibliothèque'],
    ['えいがかん', 'cinéma'],
    ['げきしょう', 'théâtre'],
    ['きょうかい', 'église'],
    ['こうえん', 'parc'],
    ['どうぶつえん', 'zoo'],
    ['ぼうし', 'chapeau'],
    ['めがね', 'lunettes'],
    ['かさ', 'parapluie'],
    ['くつ', 'chaussure'],
    ['とけい', 'montre'],
    ['でんわ', 'téléphone'],
    ['くるま', 'voiture'],
    ['はな', 'fleur'],
    ['かぎ', 'clé'],
    ['しんぶん', 'journal'],
    ['まど', 'fenêtre'],
    ['じしょ', 'dictionnaire'],
    ['したぎ', 'sous-vêtement'],
    ['ほん', 'livre'],
    ['めいし', 'carte de visite'],
    ['ばんごう', 'numéro'],
    ['てがみ', 'lettre'],
    ['うち', 'maison'],
    ['かばん', 'sac'],
    ['ざっし', 'magazine'],
    ['ひと', 'personne'],
    ['しごと', 'travail'],
    ['ひるやすみ', 'pause déjeuner'],
    ['じゅうしょ', 'adresse'],
    ['かいぎ', 'réunion'],
    ['おんがく', 'musique'],
    ['きゃく', 'client'],
    ['かびん', 'vase'],
    ['あさごはん', 'petit déjeuner'],
    ['ひるごはん', 'déjeuner'],
    ['ばんごはん', 'dîner'],
    ['げつようび', 'lundi', 'temps, jour de la semaine'],
    ['かようび', 'mardi', 'temps, jour de la semaine'],
    ['すいようび', 'mercredi', 'temps, jour de la semaine'],
    ['もくようび', 'jeudi', 'temps, jour de la semaine'],
    ['きんようび', 'vendredi', 'temps, jour de la semaine'],
    ['どようび', 'samedi', 'temps, jour de la semaine'],
    ['にちようび', 'dimanche', 'temps, jour de la semaine'],
    ['いちがつ', 'janvier', 'temps, mois de l\'année'],
    ['にがつ', 'février', 'temps, mois de l\'année'],
    ['さんがつ', 'mars', 'temps, mois de l\'année'],
    ['しがつ', 'avril', 'temps, mois de l\'année'],
    ['ごがつ', 'mai', 'temps, mois de l\'année'],
    ['ろくがつ', 'juin', 'temps, mois de l\'année'],
    ['なながつ', 'juillet', 'temps, mois de l\'année'],
    ['はちがつ', 'août', 'temps, mois de l\'année'],
    ['くがつ', 'septembre', 'temps, mois de l\'année'],
    ['じゅうがつ', 'octobre', 'temps, mois de l\'année'],
    ['じゅういちがつ', 'novembre', 'temps, mois de l\'année'],
    ['じゅうにがつ', 'décembre', 'temps, mois de l\'année'],
    ['ついたち', '1er', 'temps, jour du mois'],
    ['ふつか', '2ème', 'temps, jour du mois'],
    ['みっか', '3ème', 'temps, jour du mois'],
    ['よっか', '4ème', 'temps, jour du mois'],
    ['いつか', '5ème', 'temps, jour du mois'],
    ['むいか', '6ème', 'temps, jour du mois'],
    ['なのか', '7ème', 'temps, jour du mois'],
    ['ようか', '8ème', 'temps, jour du mois'],
    ['ここのか', '9ème', 'temps, jour du mois'],
    ['とおか', '10ème', 'temps, jour du mois'],
    ['じゅういちにち', '11ème', 'temps, jour du mois'],
    ['じゅうよっか', '14ème', 'temps, jour du mois'],
    ['はつか', '20ème', 'temps, jour du mois'],
    ['おととい', 'avant-hier', 'temps, temps relatif'],
    ['きのう', 'hier', 'temps, temps relatif'],
    ['きょう', "aujourd'hui", 'temps, temps relatif'],
    ['あした', 'demain', 'temps, temps relatif'],
    ['あさって', 'après-demain', 'temps, temps relatif'],
    ['せんせんしゅう', 'il y a 2 semaines', 'temps, temps relatif'],
    ['せんしゅう', 'la semaine dernière', 'temps, temps relatif'],
    ['こんしゅう', 'cette semaine', 'temps, temps relatif'],
    ['らいしゅう', 'la semaine prochaine', 'temps, temps relatif'],
    ['さらいしゅう', 'dans 2 semaines', 'temps, temps relatif'],
    ['せんげつ', 'le mois dernier', 'temps, temps relatif'],
    ['こんげつ', 'ce mois-ci', 'temps, temps relatif'],
    ['らいげつ', 'le mois prochain', 'temps, temps relatif'],
    ['おととし', 'il y a 2 ans', 'temps, temps relatif'],
    ['きょねん', "l'année dernière", 'temps, temps relatif'],
    ['ことし', 'cette année', 'temps, temps relatif'],
    ['らいねん', "l'année prochaine", 'temps, temps relatif'],
    ['ごぜん', 'matin', 'temps'],
    ['ごご', 'après-midi', 'temps'],
    ['しゅうまつ', 'week-end', 'temps'],
    ['がつ', "mois de l'année", 'temps'],
    ['にち', 'jour du mois', 'temps'],
    ['ひ', 'jour'],
    ['ようび', 'jour de la semaine', 'temps'],
    ['まいあさ', 'chaque matin'],
    ['まいにち', 'chaque jour'],
    ['まいばん', 'chaque soir'],
    ['たんじょうび', 'anniversaire', 'temps'],
    ['そして', 'puis'],
    ['から', 'comme, puisque, vu que'],
    ['いくら', 'combien (prix)'],
    ['じゃあ', 'alors'],
];
