<?php

declare(strict_types=1);

return [
    ['たべます', 'manger'],
    ['のみます', 'boire'],
    ['いきます', 'aller'],
    ['おきます', 'se lever'],
    ['はなします', 'parler'],
    ['します', 'faire'],
    ['ききます', 'écouter'],
    ['よみます', 'lire'],
    ['かきます', 'écrire'],
    ['みます', 'regarder'],
    ['ねます', 'se coucher'],
    ['かえります', 'rentrer, retourner'],
    ['おわります', 'terminer'],
    ['あけます', 'ouvrir'],
    ['みせます', 'montrer'],
    ['まちます', 'attendre'],
    ['きれい', 'beau, propre'],
    ['せまい', 'étroit'],
    ['おおきい', 'grand'],
    ['ちいさい', 'petit'],
    ['ながい', 'long'],
    ['みじかい', 'court'],
    ['たかい', 'cher'],
    ['やすい', 'bon marché'],
    ['あつい', 'chaud'],
    ['さむい', 'froid'],
    ['あたらしい', 'neuf, nouveau'],
    ['ふるい', 'vieux'],
    ['あかるい', 'clair'],
    ['くらい', 'sombre'],
    ['かるい', 'léger'],
    ['おもい', 'lourd'],
    ['いい', 'bien, bon'],
    ['わるい', 'mauvais'],
    ['うるさい', 'bruyant'],
    ['しずか', 'calme, tranquille'],
    ['きたない', 'sale'],
    ['ひろい', 'étendu, spacieux'],
    ['がくせい', 'étudiant'],
    ['かいしゃいん', 'employé'],
    ['ぎんこういん', 'employé de banque'],
    ['いしゃ', 'docteur'],
    ['べんごし', 'avocat'],
    ['かいけいし', 'comptable'],
    ['けんちくか', 'architecte'],
    ['ぎし', 'ingénieur'],
    ['けいかん', 'agent de police'],
    ['かんごし', 'infirmière'],
    ['はいしゃ', 'dentiste'],
    ['ひしょ', 'secrétaire'],
    ['てんいん', 'vendeur'],
    ['ぎんこう', 'banque'],
    ['ゆうびんきょく', 'bureau de poste'],
    ['がっこう', 'école'],
    ['びょういん', 'hôpital'],
    ['きっさてん', 'café'],
    ['としょかん', 'bibliothèque'],
    ['えいがかん', 'cinéma'],
    ['げきしょう', 'théâtre'],
    ['きょうかい', 'église'],
    ['こうえん', 'parc'],
    ['どうぶつえん', 'zoo'],
    ['ぼうし', 'chapeau'],
    ['めがね', 'lunettes'],
    ['かさ', 'parapluie'],
    ['くつ', 'chaussure'],
    ['とけい', 'montre'],
    ['でんわ', 'téléphone'],
    ['くるま', 'voiture'],
    ['はな', 'fleur'],
    ['かぎ', 'clé'],
    ['しんぶん', 'journal'],
    ['まど', 'fenêtre'],
    ['じしょ', 'dictionnaire'],
    ['したぎ', 'sous-vêtement'],
    ['ほん', 'livre'],
    ['めいし', 'carte de visite'],
    ['ばんごう', 'numéro'],
    ['てがみ', 'lettre'],
    ['うち', 'maison'],
    ['かばん', 'sac'],
    ['ざっし', 'magazine'],
    ['ひと', 'personne'],
    ['しごと', 'travail'],
    ['ひるやすみ', 'pause déjeuner'],
    ['じゅうしょ', 'adresse'],
    ['かいぎ', 'réunion'],
    ['おんがく', 'musique'],
    ['きゃく', 'client'],
    ['かびん', 'vase'],
    ['あさごはん', 'petit déjeuner'],
    ['ひるごはん', 'déjeuner'],
    ['ばんごはん', 'dîner'],
    ['げつようび', 'lundi'],
    ['かようび', 'mardi'],
    ['すいようび', 'mercredi'],
    ['もくようび', 'jeudi'],
    ['きんようび', 'vendredi'],
    ['どようび', 'samedi'],
    ['にちようび', 'dimanche'],
    ['いちがつ', 'janvier'],
    ['にがつ', 'février'],
    ['さんがつ', 'mars'],
    ['しがつ', 'avril'],
    ['ごがつ', 'mai'],
    ['ろくがつ', 'juin'],
    ['なながつ', 'juillet'],
    ['はちがつ', 'août'],
    ['くがつ', 'septembre'],
    ['じゅうがつ', 'octobre'],
    ['じゅういちがつ', 'novembre'],
    ['じゅうにがつ', 'décembre'],
    ['ついたち', '1er'],
    ['ふつか', '2ème'],
    ['みっか', '3ème'],
    ['よっか', '4ème'],
    ['いつか', '5ème'],
    ['むいか', '6ème'],
    ['なのか', '7ème'],
    ['ようか', '8ème'],
    ['ここのか', '9ème'],
    ['とおか', '10ème'],
    ['じゅういちにち', '11ème'],
    ['じゅうよっか', '14ème'],
    ['はつか', '20ème'],
    ['おととい', 'avant-hier'],
    ['きのう', 'hier'],
    ['きょう', "aujourd'hui"],
    ['あした', 'demain'],
    ['あさって', 'après-demain'],
    ['せんせんしゅう', 'il y a 2 semaines'],
    ['せんしゅう', 'la semaine dernière'],
    ['こんしゅう', 'cette semaine'],
    ['らいしゅう', 'la semaine prochaine'],
    ['さらいしゅう', 'dans 2 semaines'],
    ['せんげつ', 'le mois dernier'],
    ['こんげつ', 'ce mois-ci'],
    ['らいげつ', 'le mois prochain'],
    ['おととし', 'il y a 2 ans'],
    ['きょねん', "l'année dernière"],
    ['ことし', 'cette année'],
    ['らいねん', "l'année prochaine"],
    ['ごぜん', 'matin'],
    ['ごご', 'après-midi'],
    ['しゅうまつ', 'week-end'],
    ['がつ', "mois de l'année"],
    ['にち', 'jour du mois'],
    ['ひ', 'jour'],
    ['ようび', 'jour de la semaine'],
    ['まいあさ', 'chaque matin'],
    ['まいにち', 'chaque jour'],
    ['まいばん', 'chaque soir'],
    ['たんじょうび', 'anniversaire'],
    ['そして', 'puis'],
    ['から', 'comme, puisque, vu que'],
    ['いくら', 'combien (prix)'],
    ['じゃあ', 'alors'],
];
