name: Docker

on:
    push:
        paths:
            - .docker/**/*
            - compose.yaml
            - compose.ci.yaml
            - compose.prod.yaml
            - .github/workflows/docker.yml
            - justfile*

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            -   uses: extractions/setup-just@v2

            -   uses: actions/checkout@v4

            -   name: Log in to Docker Hub
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build the images
                run: just build-ci

            -   name: Push the images
                run: just push-ci
